import Head from "next/head";

export default function FooPage() {
    return(<>
    <Head>
        <title>Taishiro Portfolio Website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    </Head>

    <main>
        <p>hi</p>
    </main>
    </>
    )
}
